config/urls.py
from django.contrib import admin

from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # Main app
    path('', include('image_app.urls')),
    # Authentication
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

image_app/urls.py
from django.urls import path

from .views import (
    PhotoListView,
    PhotoTagListView,
    PhotoDetailView,
    PhotoCreateView,
    PhotoUpdateView,
    PhotoDeleteView
)

app_name = 'photo'

urlpatterns = [
    path('', PhotoListView.as_view(), name='list'),

    path('tag/<slug:tag>/', PhotoTagListView.as_view(), name='tag'),

    path('photo/<int:pk>/', PhotoDetailView.as_view(), name='detail'),

    path('photo/create/', PhotoCreateView.as_view(), name='create'),

    path('photo/<int:pk>/update/', PhotoUpdateView.as_view(), name='update'),

    path('photo/<int:pk>/delete/', PhotoDeleteView.as_view(), name='delete'),
]

users/urls.py
from django.urls import path

from django.contrib.auth.views import LogoutView

from .views import SignUpView, CustomLoginView

app_name = 'user'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', CustomLoginView.as_view(), name='login'),
    # path('logout/', LogoutView.as_view(), name='logout'),
]

image_app/models.py
'''Photoapp Models'''

from django.db import models

from django.contrib.auth import get_user_model

from taggit.managers import TaggableManager


class Photo(models.Model):
    geolocation = models.CharField(max_length=250)

    created = models.DateTimeField(auto_now_add=True)

    image = models.ImageField(upload_to='photos/')

    submitter = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    tags = TaggableManager()

users/models.py
from django.db import models

# Create your models here.

image_app/views.py
from django.shortcuts import get_object_or_404

from django.core.exceptions import PermissionDenied

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from django.urls import reverse_lazy

from .models import Photo


class PhotoListView(ListView):

    model = Photo

    template_name = 'image_app/list.html'

    context_object_name = 'photos'


class PhotoTagListView(PhotoListView):

    template_name = 'image_app/taglist.html'

    # Custom function
    def get_tag(self):
        return self.kwargs.get('tag')

    def get_queryset(self):
        return self.model.objects.filter(tags__slug=self.get_tag())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tag"] = self.get_tag()
        return context


class PhotoDetailView(DetailView):

    model = Photo

    template_name = 'image_app/detail.html'

    context_object_name = 'photo'


class PhotoCreateView(LoginRequiredMixin, CreateView):

    model = Photo

    fields = ['geolocation', 'image', 'submitter', 'tags']

    template_name = 'image_app/create.html'

    success_url = reverse_lazy('photo:list')

    def form_valid(self, form):
        form.instance.submitter = self.request.user

        return super().form_valid(form)


class UserIsSubmitter(UserPassesTestMixin):

    # Custom method
    def get_photo(self):
        return get_object_or_404(Photo, pk=self.kwargs.get('pk'))

    def test_func(self):

        if self.request.user.is_authenticated:
            return self.request.user == self.get_photo().submitter
        else:
            raise PermissionDenied('Sorry you are not allowed here')


class PhotoUpdateView(UserIsSubmitter, UpdateView):

    template_name = 'image_app/update.html'

    model = Photo

    fields = ['geolocation', 'image', 'submitter', 'tags']

    success_url = reverse_lazy('photo:list')


class PhotoDeleteView(UserIsSubmitter, DeleteView):

    template_name = 'image_app/delete.html'

    model = Photo

    success_url = reverse_lazy('photo:list')

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SignUpView(CreateView):

    template_name = 'users/signup.html'
    
    form_class = UserCreationForm

    success_url = reverse_lazy('photo:list')

    def form_valid(self, form):
        to_return = super().form_valid(form)

        user = authenticate(
            username=form.cleaned_data["username"],
            password=form.cleaned_data["password1"],
        )

        login(self.request, user)

        return to_return
    
class CustomLoginView(LoginView):
    
    template_name = 'users/login.html'

image_app/templates/image_app/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<div>
  <div>
  <p style="text-align: center; font-size: 100px; font-family: 'Rockwell Extra Bold',sans-serif">Create and Add Image</p>
  <p></p>
    <img src="https://giffiles.alphacoders.com/617/61791.gif" alt="Smiley face" width="100" height="100" style="horiz-align:center; margin:10px 515px">
</div>
  <div class="mx-auto">
  <h1 class="mt-3 text-center" style="font-size: 20px">Add image properties</h1>
</div>
<div class="form-group">
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <div>
      <p></p>
    </div>
    <button type="submit" class="btn btn-success w-20 mb-3">Add Photo</button>
  </form>
</div>
</div>
{% endblock body %}

image_app/templates/image_app/delete.html
{% extends 'base.html' %} 

{% block body %}
<div>
  <div>
  <p style="text-align: center; font-size: 100px; font-family: 'Rockwell Extra Bold',sans-serif">Delete Image</p>
  <p></p>
    <img src="https://giffiles.alphacoders.com/617/61791.gif" alt="Smiley face" width="100" height="100" style="horiz-align:center; margin:10px 515px">
</div>
<div class="form-group mx-auto">
  <h2 class="text-center">
    Are you sure you would like to delete this image?
  </h2>
  <div>
      <p></p>
    </div>
  <img src="{{photo.image.url}}" alt="" width="100%" style="horiz-align:center; margin:10px 10px"/>

<!--  <p class="text-center">Are you sure, you want to delete the photo ?</p>-->
  <div>
      <p></p>
    </div>
  <div class="form-group">
    <form
      action=""
      method="post"
      class="d-flex flex-column align-items-center justify-content-center"
    >
      {% csrf_token %}
      <div class="row">
        <div class="col">
          <a href="{% url 'photo:detail' photo.id %}" class="btn btn-primary"
            >Back</a
          >
        </div>
        <div class="col">
          <button type="submit" class="btn btn-danger">Delete</button>
        </div>
      </div>
      <div>
      <p></p>
    </div>
      <p style="text-align: center ;font-size: 20px;">Remember. If you choose to proceed with the deletion of this image. The image will be permanently deleted and cannot be reversed. Press Back to Abort operation.</p>
    </form>
  </div>
</div>

{% endblock body %}
</div>

image_app/templates/image_app/detail.html
{% extends 'base.html' %} 

{% block body %}
<div>
  <div>
  <p style="text-align: center; font-size: 100px; font-family: 'Rockwell Extra Bold'">Image Details and Share</p>
  <p></p>
    <img src="https://giffiles.alphacoders.com/617/61791.gif" alt="Smiley face" width="100" height="100" style="horiz-align:center; margin:10px 515px">
    <div>
  <img src="{{photo.image.url}}" alt="" width="100%" style="horiz-align:center; margin:10px 10px"/>
</div>
    <div>
      <p></p>
    </div>
  </div>


  <div class="mx-auto">
  {% if user == photo.submitter %}
    <p class="text-center">
      <span><a href="{% url 'photo:update' photo.id %}" class="btn btn-success w-20 mb-3">Update Image</a></span>
      <span><a href="{% url 'photo:delete' photo.id %}" class="btn btn-danger w-20 mb-3">Delete Image</a></span>
      <a href="{{request.get_absolute_uri}}" class="btn btn-primary w-20 mb-3">Share Image</a>
    </p>
  {% endif %}
</div>

  </div>
  <h4 style="text-align:center; margin: 10px">Image Details</h4>
  <h1 class="text-center">{{ photo.title }}</h1>
<div>
      <p></p>
    </div>
  <p class="text-center fw-light" style="font-family: 'Rockwell Extra Bold',sans-serif; font-size: 20px">Date and Time Uploaded: {{photo.created}} <br> Uploader: {{photo.submitter.username}}</p>
    <ul class="list-group list-group-horizontal-lg list-unstyled py-4">
      {% for tag in photo.tags.all %}
        <li><a href="{% url 'photo:tag' tag.slug %}" class="btn btn-tag list-group-item list-group-item-success">{{tag.name}}</a></li>
      {% endfor %}
    </ul>
    <p>{{ photo.description }}</p>
</div>
</div>

{% endblock body %}

image_app/templates/image_app/list.html
{% extends 'base.html' %} 

{% block body %}

<div>
  <div>
  <div>
  <p style="text-align: center; font-size: 100px; font-family: 'Rockwell Extra Bold',sans-serif">Download or Edit Image</p>
  <p></p>
    <img src="https://giffiles.alphacoders.com/617/61791.gif" alt="Smiley face" width="100" height="100" style="horiz-align:center; margin:10px 515px" >
</div>
    <p class="mt-3 text-center" style="font-size: 20px">Click on the image to edit image and see image details</p>
  <div class="row">
  {% for photo in photos %}
  <div class="col-lg-3 col-md-4 col-xs-6">
    <a href="{% url 'photo:detail' photo.id %}" class="d-block mb-4 h-100">
      <img src="{{photo.image.url}}" class="img-fluid rounded" alt="{{photo.title}}"/>
      <a href="/media/{{photo.image}}" download="photo" class="btn btn-success w-20 mb-3">Download Image</a>

    </a>
  </div>
  {% endfor %}
</div>
</div>

{% endblock body %}
</div>

image_app/templates/image_app/taglist.html
{% extends 'image_app/list.html' %}

{% block body %}

<div class="alert alert-primary">
    <h2 class="text-center">Images that have the same "{{tag}}" tag! Click on the image for more details...</h2>
</div>

{{ block.super }}

{% endblock body %}

image_app/templates/image_app/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
<div>
  <div>
  <p style="text-align: center; font-size: 100px; font-family: 'Rockwell Extra Bold',sans-serif">Download or Edit Image</p>
  <p></p>
    <img src="https://giffiles.alphacoders.com/617/61791.gif" alt="Smiley face" width="100" height="100" style="horiz-align:center; margin:10px 515px">
</div>
<div class="mx-auto">
  <h1 class="mt-3 text-center">Edit Selected Image Below</h1>
</div>
<div class="form-group">
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success mb-3">Edit Photo</button>
  </form>
</div>
{% endblock body %}
</div>

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Pic Bean</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0"
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
      integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
      crossorigin="anonymous"
    />
  </head>
  <body style="background-color: #e6ff69">
    {% include 'navbar.html' %}

    <div class="container mt-4">
    {% block body %}

    {% endblock body %}

    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-info">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'photo:list' %}">Pic Bean</a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarTogglerDemo02"
        aria-controls="navbarTogglerDemo02"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div
        class="collapse navbar-collapse flex-row-reverse"
        id="navbarTogglerDemo02"
      >
        <ul class="navbar-nav">
          {% if user.is_authenticated %}
           <li>
             <p><a href="{% url 'user:login' %}" class="btn btn-danger">Log Out</a></p>
           </li>
          <li class="nav-item">
            <a class="btn btn-primary active" href="{% url 'photo:create' %}">Add Image</a>
          </li>

          <li class="nav-item">
            <a class="btn btn-success active" href="{% url 'photo:list' %}">{{user.username}}</a>
            <p style="text-align: center; font-family: 'Rockwell Extra Bold',sans-serif">Profile</p>
          </li>

          {% else %}
  
          <li class="nav-item">
            <a href="{% url 'user:login' %}" class="btn btn-primary btn-success"
              >Sign In</a
            >
          </li>
          <li class="nav-item">
            <a href="{% url 'user:signup' %}" class="btn btn-secondary btn-danger"
            >Register</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  

users/templates/users/login.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %}

{% block body %}

<body style="background-color: #e6ff69">
  <div>
  <p style="text-align: center; font-size: 100px; font-family: 'Rockwell Extra Bold'">Login</p>
  <p></p>
    <img src="https://giffiles.alphacoders.com/617/61791.gif" alt="Smiley face" width="100" height="100" style="horiz-align:center; margin:10px 515px">
</div>
<div class="container-xxl">
  <div class="mx-auto">
  <div class="form-group">
    <form action="" method="post" style="">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-success w-20 my-3 align-content-center">Sign in</button>
    </form>
  </div>
  {% comment %}  Already Registered {% endcomment %}
  <div class="text-center w-100">
    <p class="text-muted font-weight-bold" style="font-size: 20px">
      If you don't have an account, please register HERE!
      <a href="{% url 'user:signup' %}" class="btn btn-success w-20 my-3 align-content-center">Register?</a>
    </p>
  </div>
</div>
</div>

<!--  <div>-->
<!--    <h1>-->
<!--      <span class="border border-primary">Hello World!</span>-->
<!--    </h1>-->
<!--  </div>-->

</body>

{% endblock body %}

users/templates/users/signup.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %}
{% block body %}
<div style="background-color: #e6ff69">
  <div>
  <p style="text-align: center; font-size: 100px; font-family: 'Rockwell Extra Bold',sans-serif">Create Account</p>
  <p></p>
    <img src="https://giffiles.alphacoders.com/617/61791.gif" alt="Smiley face" width="100" height="100" style="horiz-align:center; margin:10px 515px">
</div>
  <div class="mx-auto">
  <div class="form-group">
    <form action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-success w-20 my-3">Register</button>
    </form>
  </div>
  {% comment %}  Already Registered {% endcomment %}
  <div class="text-center w-100">
    <p class="text-muted font-weight-bold" style="font-size: 20px">
      If you are already Registered. Click HERE
      <a href="{% url 'user:login' %}" class="btn btn-success w-20 my-3 align-content-center"> Login </a>
    </p>
  </div>
</div>
</div>
{% endblock body %}